### ISSUE TITLE
user profiles

### ISSUE THREAD

**Issue by mrschtief** [immopoly/website#15]
Ich bin dafür auch die user profiles auf der webseite zu machen.
vielleicht erreichbar durch http://immopoly.org/user/username

hier ist das json fürs public profile

http://immopoly.appspot.com/user/profile/mrschtief.json

ich liefere am wochenende noch die persönliche geclusterte heatmap des users siehe 

https://github.com/immopoly/appengine/issues/28

**Comment by mrschtief** [comment]
User heatmap backend fertig... z.b. http://1.immopoly.appspot.com/heatmap.html oder /user/heatmap?username= momentan gibs ne 1km geclusterte map aller vermieteter wohnungen ever... koennen wir gern noch begrenzen auf letzte x oder letzte zeit x... gerne auch nur jedes 2te...

**Comment by keyboardsurfer** [comment]
@stefanhoth kommt hier noch progress?

**Comment by stefanhoth** [comment]
@keyboardsurfer eher nicht. Sorry
