### ISSUE TITLE
Top Makler monatlich/alltime

### ISSUE THREAD

**Issue by mrschtief** [immopoly/website#3]
die topx Methode kann jetzt per rankType monatliche oder alltime tops zurückliefern siehe https://github.com/immopoly/immopoly/wiki/ImmopolyAPI

**Comment by stefanhoth** [comment]
Werde mich wie besprochen drum kümmern.

**Comment by mrschtief** [comment]
Neuer ranktype http://immopoly.appspot.com/user/topx?ranktype=balanceReleaseBadge&start=0&end=10

Muss bis donnerstag abend implementiert werden

**Comment by mrschtief** [comment]
ich mach den nochmal auf, da die umschaltemöglichkeit zwischen alltime/monatlich und releasebadge noch fehlt
